name: build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest ] #, ubuntu-26.04 ]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          arch: x64

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.24
        with:
          key: ${{ runner.os }}-ccache
          max-size: 2000M
          verbose: 2

      - name: install linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libasound2-dev libxinerama-dev libx11-dev libxext-dev libfreetype-dev libwebkit2gtk-4.1-dev libglu1-mesa-dev xvfb ninja-build

      - name: configure
        run: cmake . --preset ci

      - name: build
        run: cmake --build --preset ci

      - name: pluginval
        run: cmake --build --preset ci --target pluginval_Eq

      - name: auval
        if: runner.os == 'macOS'
        run: cmake --build --preset ci --target auval_Eq
