name: Linux

on:
  push:
    branches: [ 1-CI ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-packages
      run: |
        sudo apt install libasound2-dev libxrandr-dev libxinerama-dev libxcursor-dev
    - name: cmake
      run: |
        cmake --version
        mkdir build
        cmake -B build .
    - name: build
      run: |
        echo $PWD
        cmake --build build

